jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          pip install -r requirements.txt
          pytest --maxfail=1 --disable-warnings -q

  figure-extraction:
    if: github.event_name == 'workflow_dispatch'
    runs-on: self-hosted   # GPU 서버를 GitHub Runner로 등록해 실행
    steps:
      - uses: actions/checkout@v4
      - run: |
          pip install -r requirements.txt
          python main.py --extract-figures
